### ISSUE TITLE
'/bin/sh -c pip3 install --upgrade setuptools pip' returned a non-zero code: 1

### ISSUE THREAD

**Issue by smoms** [maxtheaviator/resin-azure-iotedge-mulitcontainer#1]
I use FROM balenalib/raspberrypi3-python:3.6-jessie-build and I get this error after the build:

Step 3/11 : RUN pip3 install --upgrade setuptools pip
[iotedge]   ---> Running in ef85c9745838
[iotedge]  Traceback (most recent call last):
[iotedge]    File "/usr/local/bin/pip3", line 7, in <module>
[iotedge]      from pip._internal import main
[iotedge]    File "/usr/lib/python3/dist-packages/pip/__init__.py", line 72, in <module>
[iotedge]      from pip.log import logger
[iotedge]    File "/usr/lib/python3/dist-packages/pip/log.py", line 9, in <module>
[iotedge]      import colorama, pkg_resources
[iotedge]    File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1520, in <module>
[iotedge]      register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
[iotedge]  AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
[iotedge]
[iotedge]  Removing intermediate container ef85c9745838
[Info]     Uploading images
[iotedge]  The command '/bin/sh -c pip3 install --upgrade setuptools pip' returned a non-zero code: 1

**Comment by smoms** [comment]
I have fixed the error above.
Now when the container starts gives this error:

02.07.19 17:47:19 (+0200)  iotedge  ERROR: Error during pull for image local/azure-iotedge-runtime-resin:latest
02.07.19 17:47:19 (+0200)  iotedge  404 Client Error: Not Found ("pull access denied for local/azure-iotedge-runtime-resin, repository does not exist or may require 'docker login'")
02.07.19 17:47:19 (+0200)  iotedge  ERROR: Exiting with errors. Return code: 1

Please help.

**Comment by maxtheaviator** [comment]
Sorry for the late response. I tried to get Azure IoT Edge V1 up and running on ResinOs 2 years back. So it's far deprecated. There is IoT Edge V2 out there already, which changes a lot. "V1" is still there but not actively promoted by Microsoft.

To your issue:
`docker build -t local/azure-iotedge-runtime-resin:latest /azure-iotedge-runtime` in /iotedge/app/startIotEdgeDevice.sh is tagging a image on the local system repository. Maybe it's not on your device. Check with `docker image ls`
